## Each new term in the Fibonacci sequence is generated by adding the previous
## two terms. By starting with 1 and 2, the first 10 terms will be:
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
## By considering the terms in the Fibonacci sequence whose values do not
## exceed four million, find the sum of the even-valued terms.

def fibonnaci():
    fibList = [1, 2]
    isValid = True
    while isValid:
        indexA = len(fibList) - 1
        indexB = indexA - 1
        newValue = fibList[indexA] + fibList[indexB]
        if newValue > 4000000:
            isValid = False
        else:
            fibList.append(newValue)
    fibSum = 0
    for i in fibList:
        if i % 2 == 0:
            fibSum += i
    return(fibSum)

print(fibonnaci())